/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.ProjetoDAO;
import Javabeans.Projeto;
import Javabeans.User;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Luiz
 */
public class DeleteProject extends javax.swing.JFrame {

    /**
     * Creates new form DeleteProject
     */
    public DeleteProject() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeprojectTitle = new javax.swing.JLabel();
        searchtitle = new javax.swing.JLabel();
        projectnamefield = new javax.swing.JTextField();
        projectNameTitle = new javax.swing.JLabel();
        textareaDescription = new javax.swing.JTextArea();
        projectname_separator = new javax.swing.JSeparator();
        descriptionTitle = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        search_separator = new javax.swing.JSeparator();
        searchbutton = new javax.swing.JButton();
        deleteuserbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JLabel();
        orangebox = new javax.swing.JLabel();
        whitebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeprojectTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeprojectTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/removeproject_text.png"))); // NOI18N
        getContentPane().add(removeprojectTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 120, 50));

        searchtitle.setText("Insira o ID do projeto:");
        getContentPane().add(searchtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 20));

        projectnamefield.setEditable(false);
        projectnamefield.setToolTipText("");
        projectnamefield.setBorder(null);
        projectnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(projectnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 370, 30));

        projectNameTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/title.png"))); // NOI18N
        getContentPane().add(projectNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 100, 20));

        textareaDescription.setColumns(20);
        textareaDescription.setRows(5);
        getContentPane().add(textareaDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, 160));
        getContentPane().add(projectname_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 370, 10));

        descriptionTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/title_description.png"))); // NOI18N
        getContentPane().add(descriptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 60, 20));

        searchfield.setForeground(new java.awt.Color(153, 153, 153));
        searchfield.setText("Pesquisar projeto por ID");
        searchfield.setToolTipText("");
        searchfield.setBorder(null);
        searchfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchfieldFocusLost(evt);
            }
        });
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 20));
        getContentPane().add(search_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 10));

        searchbutton.setBackground(new java.awt.Color(60, 86, 240));
        searchbutton.setForeground(new java.awt.Color(240, 240, 240));
        searchbutton.setText("Pesquisar");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, 30));

        deleteuserbutton.setBackground(new java.awt.Color(60, 86, 240));
        deleteuserbutton.setForeground(new java.awt.Color(240, 240, 240));
        deleteuserbutton.setText("Excluir");
        deleteuserbutton.setToolTipText("");
        deleteuserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteuserbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteuserbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 130, 30));

        closebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/close_icon.png"))); // NOI18N
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 10));

        orangebox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangebox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/orange_box.png"))); // NOI18N
        getContentPane().add(orangebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        whitebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgregister/white-bg.png"))); // NOI18N
        getContentPane().add(whitebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 410, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusGained
        // TODO add your handling code here:
        //emailfield.setText("");
        if (searchfield.getText().trim().equals("Pesquisar projeto por ID")) {
            searchfield.setText("");
            searchfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_searchfieldFocusGained

    private void searchfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusLost
        // TODO add your handling code here:
        if (searchfield.getText().trim().equals("") || searchfield.getText().trim().equals("Pesquisar projeto por ID")) {
            searchfield.setText("Pesquisar projeto por ID");
            searchfield.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchfieldFocusLost

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldMouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        //obter dados do usuário
        try {
            int intProjectId = Integer.parseInt(searchfield.getText());
            

            // Executando o select
            ProjetoDAO dao = new ProjetoDAO();
            List<Projeto> listProjects = dao.consultarProjeto(intProjectId);

            for (Projeto p : listProjects) {
                projectnamefield.setText(p.getNomeProjeto());
                textareaDescription.setText(p.getDescProjeto());
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao encontrar sua conta: " + error);
        }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void deleteuserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteuserbuttonActionPerformed
        try {
            int intProjetoId = Integer.parseInt(searchfield.getText());
            String strProjectName = projectnamefield.getText();
            String strDescription = textareaDescription.getText();;

            Projeto obj = new Projeto();

            obj.setIdProjeto(intProjetoId);
            obj.setNomeProjeto(strProjectName);                           // Nome do projeto
            obj.setDescProjeto(strDescription);                           // Descrição do projeto

            // Executando o delete
            ProjetoDAO daoExcluir = new ProjetoDAO();

            daoExcluir.excluirProjeto(obj);
            JOptionPane.showMessageDialog(null, "O projeto foi excluido com sucesso.");
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir o projeto conta: " + error);
        }
    }//GEN-LAST:event_deleteuserbuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void projectnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectnamefieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel closebutton;
    private javax.swing.JButton deleteuserbutton;
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JLabel orangebox;
    private javax.swing.JLabel projectNameTitle;
    private javax.swing.JSeparator projectname_separator;
    private javax.swing.JTextField projectnamefield;
    private javax.swing.JLabel removeprojectTitle;
    private javax.swing.JSeparator search_separator;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel searchtitle;
    private javax.swing.JTextArea textareaDescription;
    private javax.swing.JLabel whitebg;
    // End of variables declaration//GEN-END:variables
}
