/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

//import Classes.ConnectionFactory;
import DAO.RequisitoDAO;
import DAO.UserDAO;
import JDBC.ConnectorFactory;
import Javabeans.Requisito;
import Javabeans.User;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Luiz
 */
public class DeleteRequisito extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    //Cria um novo objeto para o metodo de classes
    //Classes.User User = new Classes.User();

    //Cria uma variável para armazenar o diretorio da foto de perfil
    String imagePath = null;

    public DeleteRequisito() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeTitle = new javax.swing.JLabel();
        searchtitle = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        search_separator = new javax.swing.JSeparator();
        searchbutton = new javax.swing.JButton();
        requisitIdfield = new javax.swing.JTextField();
        idseparator = new javax.swing.JSeparator();
        requisitnamefield = new javax.swing.JTextField();
        nameseparator = new javax.swing.JSeparator();
        requisitfunctionalityfield = new javax.swing.JTextField();
        functionalityseparator = new javax.swing.JSeparator();
        requisitauthorfield = new javax.swing.JTextField();
        authorseparator = new javax.swing.JSeparator();
        textareaDescription = new javax.swing.JTextArea();
        registerbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JLabel();
        orangebox = new javax.swing.JLabel();
        whitebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        removeTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/deleterequisito_text.png"))); // NOI18N
        getContentPane().add(removeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 150, 50));

        searchtitle.setText("Insira o ID do requisito:");
        getContentPane().add(searchtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, 20));

        searchfield.setForeground(new java.awt.Color(153, 153, 153));
        searchfield.setText("Pesquisar requisito por ID");
        searchfield.setToolTipText("");
        searchfield.setBorder(null);
        searchfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchfieldFocusLost(evt);
            }
        });
        searchfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchfieldMouseClicked(evt);
            }
        });
        searchfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfieldActionPerformed(evt);
            }
        });
        getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 20));
        getContentPane().add(search_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 260, 10));

        searchbutton.setBackground(new java.awt.Color(60, 86, 240));
        searchbutton.setForeground(new java.awt.Color(240, 240, 240));
        searchbutton.setText("Pesquisar");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 100, 30));

        requisitIdfield.setEditable(false);
        requisitIdfield.setBackground(new java.awt.Color(255, 255, 255));
        requisitIdfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitIdfield.setText("Identificador Requisito");
        requisitIdfield.setBorder(null);
        requisitIdfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitIdfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitIdfieldFocusLost(evt);
            }
        });
        requisitIdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitIdfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitIdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, 30));
        getContentPane().add(idseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 370, 10));

        requisitnamefield.setEditable(false);
        requisitnamefield.setBackground(new java.awt.Color(255, 255, 255));
        requisitnamefield.setForeground(new java.awt.Color(153, 153, 153));
        requisitnamefield.setText("Nome do requisito");
        requisitnamefield.setBorder(null);
        requisitnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitnamefieldFocusLost(evt);
            }
        });
        requisitnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 380, 30));
        getContentPane().add(nameseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 370, 10));

        requisitfunctionalityfield.setEditable(false);
        requisitfunctionalityfield.setBackground(new java.awt.Color(255, 255, 255));
        requisitfunctionalityfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitfunctionalityfield.setText("Funcionalidades");
        requisitfunctionalityfield.setBorder(null);
        requisitfunctionalityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitfunctionalityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitfunctionalityfieldFocusLost(evt);
            }
        });
        requisitfunctionalityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitfunctionalityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitfunctionalityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 380, 30));
        getContentPane().add(functionalityseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 370, 10));

        requisitauthorfield.setEditable(false);
        requisitauthorfield.setBackground(new java.awt.Color(255, 255, 255));
        requisitauthorfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitauthorfield.setText("Nome do autor");
        requisitauthorfield.setBorder(null);
        requisitauthorfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitauthorfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitauthorfieldFocusLost(evt);
            }
        });
        requisitauthorfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitauthorfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitauthorfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 380, 30));
        getContentPane().add(authorseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 370, 10));

        textareaDescription.setEditable(false);
        textareaDescription.setColumns(20);
        textareaDescription.setForeground(new java.awt.Color(153, 153, 153));
        textareaDescription.setRows(5);
        textareaDescription.setText("Descrição");
        textareaDescription.setToolTipText("");
        getContentPane().add(textareaDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 380, 110));

        registerbutton.setBackground(new java.awt.Color(60, 86, 240));
        registerbutton.setForeground(new java.awt.Color(240, 240, 240));
        registerbutton.setText("Remover");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 130, 30));

        closebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/close_icon.png"))); // NOI18N
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 10));

        orangebox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangebox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/orange_box.png"))); // NOI18N
        getContentPane().add(orangebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 50));

        whitebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgregister/white-bg.png"))); // NOI18N
        getContentPane().add(whitebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 410, 530));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed

        try {
            String strNameRequisit = requisitnamefield.getText();
            //String strModule = requisitmodule.getText();
            String strFunctionality = requisitfunctionalityfield.getText();
            String strAuthor = requisitauthorfield.getText();
            //int intVersion = Integer.parseInt(requisitversionfield.getText());
            //String strPriority = requisitpriorityfield.getText();
            //String strComplexity = requisitcomplexityfield.getText();
            //int intTime = Integer.parseInt(requisiteffortfield.getText());
            //int strStatus = requisitstatusfield.getSelectedIndex();
            //String strFase = requisitfasefield.getText();
            String strDescription = textareaDescription.getText();

            //Verificacao dos campos preenchidos
            if (verifyFields()) {

                //  Chamada do objeto dao para checagem do usuario
                RequisitoDAO daocheck = new RequisitoDAO();

                // Verificar se o usuario ja existe no sistema
                if (daocheck.checarRequisito(strNameRequisit, 1)) {
                    JOptionPane.showMessageDialog(null, "Esse nome de requisito já existe. Por favor, escolha outro nome", "Falha na criação do requisito", 2);
                } else {
                    // Continua com o cadastro do usuario
                    Requisito obj = new Requisito();
                    obj.setNomeReq(strNameRequisit);                           // Nome Completo
                    //obj.setModReq(strModule);                               // Nome do Usuario
                    obj.setFuncReq(strFunctionality);                                     // Email
                    obj.setAutorReq(strAuthor);                         // Telefone
                    //obj.setVersaoReq(intVersion);   // Password
                    //obj.setPrioridadeReq(strPriority);   // Password
                    //obj.setCompReq(strComplexity);
                    //obj.setHoraReq(intTime);
                    //obj.setEstadoReq(strStatus);
                    //obj.setFaseReq(strFase);
                    obj.setDescricao(strDescription);
                    
                    //Cadastrar Requisito
                    UserDAO dao = new UserDAO();
                    //dao.cadastrarUsuario(obj);
                    JOptionPane.showMessageDialog(null, "Sua conta foi criada com sucesso.");

                }
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar seu requisito: " + error);
        }


    }//GEN-LAST:event_registerbuttonActionPerformed

    private void requisitnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitnamefieldFocusGained
        // TODO add your handling code here:
        //        if (requisitnamefield.getText().trim().equals("Insira o nome do projeto")) {
            //            requisitnamefield.setText("");
            //            requisitnamefield.setForeground(Color.black);
            //        }
    }//GEN-LAST:event_requisitnamefieldFocusGained

    private void requisitnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitnamefieldFocusLost
        // TODO add your handling code here:
        //        if (requisitnamefield.getText().trim().equals("") || requisitnamefield.getText().trim().equals("Insira o nome do projeto")) {
            //            requisitnamefield.setText("Insira o nome do projeto");
            //            requisitnamefield.setForeground(new Color(153, 153, 153));
            //        }
    }//GEN-LAST:event_requisitnamefieldFocusLost

    private void requisitnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitnamefieldActionPerformed

    private void requisitfunctionalityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldFocusGained

    private void requisitfunctionalityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldFocusLost

    private void requisitfunctionalityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldActionPerformed

    private void requisitauthorfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitauthorfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldFocusGained

    private void requisitauthorfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitauthorfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldFocusLost

    private void requisitauthorfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitauthorfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldActionPerformed

    private void requisitIdfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitIdfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitIdfieldFocusGained

    private void requisitIdfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitIdfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitIdfieldFocusLost

    private void requisitIdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitIdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitIdfieldActionPerformed

    private void searchfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusGained
        // TODO add your handling code here:
        //emailfield.setText("");
        if (searchfield.getText().trim().equals("Pesquisar projeto por ID")) {
            searchfield.setText("");
            searchfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_searchfieldFocusGained

    private void searchfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusLost
        // TODO add your handling code here:
        if (searchfield.getText().trim().equals("") || searchfield.getText().trim().equals("Pesquisar projeto por ID")) {
            searchfield.setText("Pesquisar projeto por ID");
            searchfield.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_searchfieldFocusLost

    private void searchfieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchfieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldMouseClicked

    private void searchfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfieldActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        //obter dados do usuário
        try {
            int intRequisitId = Integer.parseInt(searchfield.getText());
            int intProjectId = 1;

            // Executando o select
            RequisitoDAO dao = new RequisitoDAO();
            List<Requisito> listRequisitos = dao.consultarRequisito(intRequisitId,intProjectId);

            for (Requisito p : listRequisitos) {
                requisitIdfield.setText(p.getIdReq());
                requisitnamefield.setText(p.getNomeReq());
                requisitfunctionalityfield.setText(p.getFuncReq());
                requisitauthorfield.setText(p.getAutorReq());
                textareaDescription.setText(p.getDescricao());
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao encontrar o requisito: " + error);
        }
    }//GEN-LAST:event_searchbuttonActionPerformed
    public boolean verifyFields() {

        //Declaracao das Variaveis
        String strNameReq = requisitnamefield.getText();
        //String strModule = requisitmodule.getText();
        String strFunctionality = requisitfunctionalityfield.getText();
        String strAuthor = requisitauthorfield.getText();
        //String strVersion = requisitversionfield.getText();
        //String strPriority = requisitpriorityfield.getText();
        //String strComplexity = requisitcomplexityfield.getText();
        //String strTime = requisiteffortfield.getText();
        //int strStatus = requisitstatusfield.getSelectedIndex();
        //String strFase = requisitfasefield.getText();
        String strDescription = textareaDescription.getText();

        //Checando se todos os campos obrigatorios foram preenchidos
//        if (strNameReq.trim().equals("") || strModule.trim().equals("") || strFunctionality.trim().equals("") || strAuthor.trim().equals("")
//                || strVersion.trim().equals("") || strPriority.trim().equals("") || strComplexity.trim().equals("") || strTime.trim().equals("")
//                || strStatus == 0 || strFase.trim().equals("") || strDescription.trim().equals("")) {
//            JOptionPane.showMessageDialog(null, "Um ou mais campos estão vazios", "Campos vazios", 2);
//            return false;
//        } //Checando se ambas as senhas são iguais
////        else if (!strPwd1.equals(strPwd2)) {
////            JOptionPane.showMessageDialog(null, "As senhas não coincidem", "Confirmar senha", 2);
////            return false;
////        } //Caso todas as verificacoes esteja corretas 
//        else {
//            return true;
//        }
        return false;
    }

    //Criar uma função para checar se o usuário já existe na base de dados
    public boolean checkUsername(String username) {

        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;

        String query = "SELECT * FROM `usuarios` WHERE `name_user` = ?";

        try {
            st = ConnectorFactory.conecta().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();

            if (rs.next()) {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Esse nome de usuário já existe. Por favor, escolha outro nome", "Falha na criação do usuário", 2);
            }

        } catch (SQLException ex) {
            //Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        return username_exist;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRequisito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator authorseparator;
    private javax.swing.JLabel closebutton;
    private javax.swing.JSeparator functionalityseparator;
    private javax.swing.JSeparator idseparator;
    private javax.swing.JSeparator nameseparator;
    private javax.swing.JLabel orangebox;
    private javax.swing.JButton registerbutton;
    private javax.swing.JLabel removeTitle;
    private javax.swing.JTextField requisitIdfield;
    private javax.swing.JTextField requisitauthorfield;
    private javax.swing.JTextField requisitfunctionalityfield;
    private javax.swing.JTextField requisitnamefield;
    private javax.swing.JSeparator search_separator;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel searchtitle;
    private javax.swing.JTextArea textareaDescription;
    private javax.swing.JLabel whitebg;
    // End of variables declaration//GEN-END:variables
}
