/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

//import Classes.ConnectionFactory;
import DAO.RequisitoDAO;
import DAO.UserDAO;
import JDBC.ConnectorFactory;
import Javabeans.Requisito;
import Javabeans.User;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jose Luiz
 */
public class EditRequisito extends javax.swing.JFrame {

    /**
     * Creates new form AddUser
     */
    //Cria um novo objeto para o metodo de classes
    //Classes.User User = new Classes.User();

    //Cria uma variável para armazenar o diretorio da foto de perfil
    String imagePath = null;

    public EditRequisito() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editTtitle = new javax.swing.JLabel();
        searchfield = new javax.swing.JTextField();
        search_separator = new javax.swing.JSeparator();
        searchbutton = new javax.swing.JButton();
        searchtitle = new javax.swing.JLabel();
        separator = new javax.swing.JSeparator();
        identificafield = new javax.swing.JTextField();
        identificaseparator = new javax.swing.JSeparator();
        requisitnamefield = new javax.swing.JTextField();
        nameseparator = new javax.swing.JSeparator();
        requisitmodule = new javax.swing.JTextField();
        tmoduleseparator = new javax.swing.JSeparator();
        requisitfunctionalityfield = new javax.swing.JTextField();
        functionalityseparator = new javax.swing.JSeparator();
        requisitauthorfield = new javax.swing.JTextField();
        authorseparator = new javax.swing.JSeparator();
        requisitversionfield = new javax.swing.JTextField();
        versionseparator = new javax.swing.JSeparator();
        requisitpriorityfield = new javax.swing.JTextField();
        priorityseparator = new javax.swing.JSeparator();
        requisitcomplexityfield = new javax.swing.JTextField();
        complexityseparator = new javax.swing.JSeparator();
        requisiteffortfield = new javax.swing.JTextField();
        effortseparator = new javax.swing.JSeparator();
        requisitstatusfield = new javax.swing.JComboBox<>();
        requisitfasefield = new javax.swing.JTextField();
        faseseparator = new javax.swing.JSeparator();
        textareaDescription = new javax.swing.JTextArea();
        registerbutton = new javax.swing.JButton();
        closebutton = new javax.swing.JLabel();
        orangebox = new javax.swing.JLabel();
        whitebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(860, 550));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editTtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editTtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/editrequisito_text.png"))); // NOI18N
        getContentPane().add(editTtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 230, 50));

        searchfield.setForeground(new java.awt.Color(153, 153, 153));
        searchfield.setText("Pesquisar usuário por ID");
        searchfield.setToolTipText("");
        searchfield.setBorder(null);
        searchfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchfieldFocusGained(evt);
            }
        });
        getContentPane().add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));
        getContentPane().add(search_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 10));

        searchbutton.setBackground(new java.awt.Color(60, 86, 240));
        searchbutton.setForeground(new java.awt.Color(240, 240, 240));
        searchbutton.setText("Pesquisar");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 30));

        searchtitle.setText("Insira o ID do usuário:");
        getContentPane().add(searchtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 20));

        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 20, 500));

        identificafield.setForeground(new java.awt.Color(153, 153, 153));
        identificafield.setText("Insira o identificador do requisito");
        identificafield.setToolTipText("");
        identificafield.setBorder(null);
        identificafield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                identificafieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                identificafieldFocusLost(evt);
            }
        });
        identificafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificafieldActionPerformed(evt);
            }
        });
        getContentPane().add(identificafield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 30));
        getContentPane().add(identificaseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 370, 10));

        requisitnamefield.setForeground(new java.awt.Color(153, 153, 153));
        requisitnamefield.setText("Insira o nome do requisito");
        requisitnamefield.setBorder(null);
        requisitnamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitnamefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitnamefieldFocusLost(evt);
            }
        });
        requisitnamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitnamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitnamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 370, 30));
        getContentPane().add(nameseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 370, 10));

        requisitmodule.setForeground(new java.awt.Color(153, 153, 153));
        requisitmodule.setText("Insira o nome do modulo");
        requisitmodule.setBorder(null);
        requisitmodule.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitmoduleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitmoduleFocusLost(evt);
            }
        });
        requisitmodule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitmoduleActionPerformed(evt);
            }
        });
        getContentPane().add(requisitmodule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 370, 30));
        getContentPane().add(tmoduleseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 370, 10));

        requisitfunctionalityfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitfunctionalityfield.setText("Insira as funcionalidades");
        requisitfunctionalityfield.setBorder(null);
        requisitfunctionalityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitfunctionalityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitfunctionalityfieldFocusLost(evt);
            }
        });
        requisitfunctionalityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitfunctionalityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitfunctionalityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 370, 30));
        getContentPane().add(functionalityseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 370, 10));

        requisitauthorfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitauthorfield.setText("Insira o nome do autor");
        requisitauthorfield.setBorder(null);
        requisitauthorfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitauthorfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitauthorfieldFocusLost(evt);
            }
        });
        requisitauthorfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitauthorfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitauthorfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 370, 30));
        getContentPane().add(authorseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 370, 10));

        requisitversionfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitversionfield.setText("Insira a versão");
        requisitversionfield.setBorder(null);
        requisitversionfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitversionfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitversionfieldFocusLost(evt);
            }
        });
        requisitversionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitversionfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitversionfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 370, 30));
        getContentPane().add(versionseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 370, 10));

        requisitpriorityfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitpriorityfield.setText("Insira a prioridade");
        requisitpriorityfield.setBorder(null);
        requisitpriorityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitpriorityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitpriorityfieldFocusLost(evt);
            }
        });
        requisitpriorityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitpriorityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitpriorityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 370, 30));
        getContentPane().add(priorityseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 370, 10));

        requisitcomplexityfield.setForeground(new java.awt.Color(153, 153, 153));
        requisitcomplexityfield.setText("Insira a complexidade");
        requisitcomplexityfield.setBorder(null);
        requisitcomplexityfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitcomplexityfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitcomplexityfieldFocusLost(evt);
            }
        });
        requisitcomplexityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitcomplexityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitcomplexityfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 370, 30));
        getContentPane().add(complexityseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 370, 10));

        requisiteffortfield.setForeground(new java.awt.Color(153, 153, 153));
        requisiteffortfield.setText("Esforço estimado (em horas)");
        requisiteffortfield.setBorder(null);
        requisiteffortfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisiteffortfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisiteffortfieldFocusLost(evt);
            }
        });
        requisiteffortfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisiteffortfieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisiteffortfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 370, 30));
        getContentPane().add(effortseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 370, 10));

        requisitstatusfield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o estado do requisito", "Especificado", "Em Andamento", "Finalizado", " " }));
        requisitstatusfield.setBorder(null);
        getContentPane().add(requisitstatusfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 370, 30));

        requisitfasefield.setForeground(new java.awt.Color(153, 153, 153));
        requisitfasefield.setText("Insira a fase");
        requisitfasefield.setBorder(null);
        requisitfasefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                requisitfasefieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                requisitfasefieldFocusLost(evt);
            }
        });
        requisitfasefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requisitfasefieldActionPerformed(evt);
            }
        });
        getContentPane().add(requisitfasefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 370, 30));
        getContentPane().add(faseseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 370, 10));

        textareaDescription.setColumns(20);
        textareaDescription.setForeground(new java.awt.Color(153, 153, 153));
        textareaDescription.setRows(5);
        textareaDescription.setText("Insira a descrição");
        textareaDescription.setToolTipText("");
        getContentPane().add(textareaDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 370, 100));

        registerbutton.setBackground(new java.awt.Color(60, 86, 240));
        registerbutton.setForeground(new java.awt.Color(240, 240, 240));
        registerbutton.setText("Editar");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 120, 30));

        closebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/close_icon.png"))); // NOI18N
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 10, 10));

        orangebox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/orange_box.png"))); // NOI18N
        getContentPane().add(orangebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 50));

        whitebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/panel_box.png"))); // NOI18N
        getContentPane().add(whitebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 870, 550));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed

        try {
            String strNameRequisit = requisitnamefield.getText();
            String strModule = requisitmodule.getText();
            String strFunctionality = requisitfunctionalityfield.getText();
            String strAuthor = requisitauthorfield.getText();
            int intVersion = Integer.parseInt(requisitversionfield.getText());
            String strPriority = requisitpriorityfield.getText();
            String strComplexity = requisitcomplexityfield.getText();
            int intTime = Integer.parseInt(requisiteffortfield.getText());
            int strStatus = requisitstatusfield.getSelectedIndex();
            String strFase = requisitfasefield.getText();
            String strDescription = textareaDescription.getText();

            //Verificacao dos campos preenchidos
            if (verifyFields()) {

                //  Chamada do objeto dao para checagem do usuario
                RequisitoDAO daocheck = new RequisitoDAO();

                // Verificar se o usuario ja existe no sistema
                if (daocheck.checarRequisito(strNameRequisit, 1)) {
                    JOptionPane.showMessageDialog(null, "Esse nome de requisito já existe. Por favor, escolha outro nome", "Falha na criação do requisito", 2);
                } else {
                    // Continua com o cadastro do usuario
                    Requisito obj = new Requisito();
                    obj.setNomeReq(strNameRequisit);                           // Nome Completo
                    obj.setModReq(strModule);                               // Nome do Usuario
                    obj.setFuncReq(strFunctionality);                                     // Email
                    obj.setAutorReq(strAuthor);                         // Telefone
                    obj.setVersaoReq(intVersion);   // Password
                    obj.setPrioridadeReq(strPriority);   // Password
                    obj.setCompReq(strComplexity);
                    obj.setHoraReq(intTime);
                    obj.setEstadoReq(strStatus);
                    obj.setFaseReq(strFase);
                    obj.setDescricao(strDescription);
                    
                    //Cadastrar Requisito
                    UserDAO dao = new UserDAO();
                    //dao.cadastrarUsuario(obj);
                    JOptionPane.showMessageDialog(null, "Sua conta foi criada com sucesso.");

                }
            }
            
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar seu requisito: " + error);
        }


    }//GEN-LAST:event_registerbuttonActionPerformed

    private void requisitnamefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitnamefieldFocusGained
        // TODO add your handling code here:
        //        if (requisitnamefield.getText().trim().equals("Insira o nome do projeto")) {
            //            requisitnamefield.setText("");
            //            requisitnamefield.setForeground(Color.black);
            //        }
    }//GEN-LAST:event_requisitnamefieldFocusGained

    private void requisitnamefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitnamefieldFocusLost
        // TODO add your handling code here:
        //        if (requisitnamefield.getText().trim().equals("") || requisitnamefield.getText().trim().equals("Insira o nome do projeto")) {
            //            requisitnamefield.setText("Insira o nome do projeto");
            //            requisitnamefield.setForeground(new Color(153, 153, 153));
            //        }
    }//GEN-LAST:event_requisitnamefieldFocusLost

    private void requisitnamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitnamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitnamefieldActionPerformed

    private void requisitmoduleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitmoduleFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitmoduleFocusGained

    private void requisitmoduleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitmoduleFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitmoduleFocusLost

    private void requisitmoduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitmoduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitmoduleActionPerformed

    private void requisitfunctionalityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldFocusGained

    private void requisitfunctionalityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldFocusLost

    private void requisitfunctionalityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitfunctionalityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfunctionalityfieldActionPerformed

    private void requisitauthorfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitauthorfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldFocusGained

    private void requisitauthorfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitauthorfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldFocusLost

    private void requisitauthorfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitauthorfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitauthorfieldActionPerformed

    private void requisitversionfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitversionfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitversionfieldFocusGained

    private void requisitversionfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitversionfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitversionfieldFocusLost

    private void requisitversionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitversionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitversionfieldActionPerformed

    private void requisitpriorityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitpriorityfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitpriorityfieldFocusGained

    private void requisitpriorityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitpriorityfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitpriorityfieldFocusLost

    private void requisitpriorityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitpriorityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitpriorityfieldActionPerformed

    private void requisitcomplexityfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitcomplexityfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitcomplexityfieldFocusGained

    private void requisitcomplexityfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitcomplexityfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitcomplexityfieldFocusLost

    private void requisitcomplexityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitcomplexityfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitcomplexityfieldActionPerformed

    private void requisiteffortfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisiteffortfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisiteffortfieldFocusGained

    private void requisiteffortfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisiteffortfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisiteffortfieldFocusLost

    private void requisiteffortfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisiteffortfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisiteffortfieldActionPerformed

    private void requisitfasefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfasefieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfasefieldFocusGained

    private void requisitfasefieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_requisitfasefieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfasefieldFocusLost

    private void requisitfasefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requisitfasefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requisitfasefieldActionPerformed

    private void identificafieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_identificafieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_identificafieldFocusGained

    private void identificafieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_identificafieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_identificafieldFocusLost

    private void identificafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificafieldActionPerformed

    private void searchfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchfieldFocusGained
        // TODO add your handling code here:
        if (searchfield.getText().trim().equals("Pesquisar usuário por ID")) {
            searchfield.setText("");
            searchfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_searchfieldFocusGained

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed

        //obter dados do requisito
        

    }//GEN-LAST:event_searchbuttonActionPerformed
    public boolean verifyFields() {

        //Declaracao das Variaveis
        String strNameReq = requisitnamefield.getText();
        String strModule = requisitmodule.getText();
        String strFunctionality = requisitfunctionalityfield.getText();
        String strAuthor = requisitauthorfield.getText();
        String strVersion = requisitversionfield.getText();
        String strPriority = requisitpriorityfield.getText();
        String strComplexity = requisitcomplexityfield.getText();
        String strTime = requisiteffortfield.getText();
        int strStatus = requisitstatusfield.getSelectedIndex();
        String strFase = requisitfasefield.getText();
        String strDescription = textareaDescription.getText();

        //Checando se todos os campos obrigatorios foram preenchidos
        if (strNameReq.trim().equals("") || strModule.trim().equals("") || strFunctionality.trim().equals("") || strAuthor.trim().equals("")
                || strVersion.trim().equals("") || strPriority.trim().equals("") || strComplexity.trim().equals("") || strTime.trim().equals("")
                || strStatus == 0 || strFase.trim().equals("") || strDescription.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Um ou mais campos estão vazios", "Campos vazios", 2);
            return false;
        } //Checando se ambas as senhas são iguais
//        else if (!strPwd1.equals(strPwd2)) {
//            JOptionPane.showMessageDialog(null, "As senhas não coincidem", "Confirmar senha", 2);
//            return false;
//        } //Caso todas as verificacoes esteja corretas 
        else {
            return true;
        }
    }

    //Criar uma função para checar se o usuário já existe na base de dados
    public boolean checkUsername(String username) {

        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;

        String query = "SELECT * FROM `usuarios` WHERE `name_user` = ?";

        try {
            st = ConnectorFactory.conecta().prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();

            if (rs.next()) {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "Esse nome de usuário já existe. Por favor, escolha outro nome", "Falha na criação do usuário", 2);
            }

        } catch (SQLException ex) {
            //Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }

        return username_exist;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Motif".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRequisito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRequisito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator authorseparator;
    private javax.swing.JLabel closebutton;
    private javax.swing.JSeparator complexityseparator;
    private javax.swing.JLabel editTtitle;
    private javax.swing.JSeparator effortseparator;
    private javax.swing.JSeparator faseseparator;
    private javax.swing.JSeparator functionalityseparator;
    private javax.swing.JTextField identificafield;
    private javax.swing.JSeparator identificaseparator;
    private javax.swing.JSeparator nameseparator;
    private javax.swing.JLabel orangebox;
    private javax.swing.JSeparator priorityseparator;
    private javax.swing.JButton registerbutton;
    private javax.swing.JTextField requisitauthorfield;
    private javax.swing.JTextField requisitcomplexityfield;
    private javax.swing.JTextField requisiteffortfield;
    private javax.swing.JTextField requisitfasefield;
    private javax.swing.JTextField requisitfunctionalityfield;
    private javax.swing.JTextField requisitmodule;
    private javax.swing.JTextField requisitnamefield;
    private javax.swing.JTextField requisitpriorityfield;
    private javax.swing.JComboBox<String> requisitstatusfield;
    private javax.swing.JTextField requisitversionfield;
    private javax.swing.JSeparator search_separator;
    private javax.swing.JButton searchbutton;
    private javax.swing.JTextField searchfield;
    private javax.swing.JLabel searchtitle;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextArea textareaDescription;
    private javax.swing.JSeparator tmoduleseparator;
    private javax.swing.JSeparator versionseparator;
    private javax.swing.JLabel whitebg;
    // End of variables declaration//GEN-END:variables
}
