/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.ProjetoDAO;
import Javabeans.Projeto;
//import DAO.UserDAO;
import Javabeans.User;
import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jose Luiz
 */
public class ProjectsPanel extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public void Listar() {
        try {
            // Executando o select
            ProjetoDAO dao = new ProjetoDAO();
            List<Projeto> listProjetos = dao.listarProjetos();

            // Inserindo os dados na tabela 
            DefaultTableModel model = (DefaultTableModel) jTableProjetos.getModel();
            //zera todas as linhas para limpeza da tabela
            model.setNumRows(0);

            for (Projeto p : listProjetos) {
                model.addRow(new Object[]{
                    p.getIdProjeto(),
                    p.getNomeProjeto(),
                    p.getDescProjeto(),
                    //p.getProprietarioProjeto()
                });
            }

        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o projeto: " + error);
        }
    }


    public ProjectsPanel() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        newprojectbuttonSt1.setVisible(false);
        newprojectbuttonSt2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counter = new javax.swing.JLabel();
        counter_box = new javax.swing.JLabel();
        pfpArea = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newprojectbuttonSt2 = new javax.swing.JLabel();
        newprojectbuttonSt1 = new javax.swing.JLabel();
        newprojectbutton = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        jTableProjetos = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        userLink = new javax.swing.JLabel();
        projectLink = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bluebg = new javax.swing.JLabel();
        whitebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        counter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        counter.setForeground(new java.awt.Color(255, 255, 255));
        counter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter.setToolTipText("");
        getContentPane().add(counter, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 60, 10, 30));

        counter_box.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counter_box.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgusers/box_counter.png"))); // NOI18N
        getContentPane().add(counter_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 40, 30));

        pfpArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pfpArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgusers/pfp.png"))); // NOI18N
        getContentPane().add(pfpArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 250, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/guide_title.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 210, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/guide_properties.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 165, 980, 50));

        newprojectbuttonSt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newprojectbuttonSt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/newproject_button_st2.png"))); // NOI18N
        newprojectbuttonSt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newprojectbuttonSt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newprojectbuttonSt2MouseExited(evt);
            }
        });
        getContentPane().add(newprojectbuttonSt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 700, 70, 80));

        newprojectbuttonSt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newprojectbuttonSt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgprojects/newproject_button_st1.png"))); // NOI18N
        newprojectbuttonSt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newprojectbuttonSt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newprojectbuttonSt1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newprojectbuttonSt1MouseExited(evt);
            }
        });
        getContentPane().add(newprojectbuttonSt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 700, 70, 80));

        newprojectbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newprojectbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/newproject_button.png"))); // NOI18N
        newprojectbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newprojectbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newprojectbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newprojectbuttonMouseEntered(evt);
            }
        });
        getContentPane().add(newprojectbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 700, 70, 80));

        editButton.setBackground(new java.awt.Color(60, 86, 240));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Editar projeto");
        editButton.setActionCommand("Editarprojeto");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 740, 150, 30));

        removeButton.setBackground(new java.awt.Color(60, 86, 240));
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Remover projeto");
        removeButton.setToolTipText("");
        removeButton.setActionCommand("Remover projeto");
        removeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, 150, 30));

        jTableProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome do projeto", "Descrição", "Usuário proprietário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProjetos.setRowHeight(50);
        jTableProjetos.getTableHeader().setReorderingAllowed(false);
        getContentPane().add(jTableProjetos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 215, -1, -1));
        if (jTableProjetos.getColumnModel().getColumnCount() > 0) {
            jTableProjetos.getColumnModel().getColumn(0).setResizable(false);
            jTableProjetos.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableProjetos.getColumnModel().getColumn(1).setResizable(false);
            jTableProjetos.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTableProjetos.getColumnModel().getColumn(2).setResizable(false);
            jTableProjetos.getColumnModel().getColumn(2).setPreferredWidth(500);
            jTableProjetos.getColumnModel().getColumn(3).setResizable(false);
            jTableProjetos.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        updateButton.setBackground(new java.awt.Color(60, 86, 240));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Atualizar");
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 150, 30));

        userLink.setBackground(new java.awt.Color(60, 86, 240));
        userLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgusers/users.png"))); // NOI18N
        userLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userLink.setOpaque(true);
        userLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userLinkMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userLinkMouseReleased(evt);
            }
        });
        getContentPane().add(userLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 230, 370, 70));

        projectLink.setBackground(new java.awt.Color(60, 86, 240));
        projectLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgusers/projects.png"))); // NOI18N
        projectLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        projectLink.setOpaque(true);
        projectLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                projectLinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                projectLinkMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                projectLinkMouseReleased(evt);
            }
        });
        getContentPane().add(projectLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 300, 370, 70));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/logo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 250, 130));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/title.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 170, 50));

        bluebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/blue_box.png"))); // NOI18N
        getContentPane().add(bluebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 790));

        whitebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgmenu/white_bg.png"))); // NOI18N
        getContentPane().add(whitebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1030, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newprojectbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newprojectbuttonMouseClicked
        // TODO add your handling code here:
        AddProject ap = new AddProject();
        ap.setVisible(true);
        ap.pack();
        ap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_newprojectbuttonMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Listando dados da tabela
        Listar();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Listar();
        
        String contador = Integer.toString(jTableProjetos.getModel().getRowCount());
        counter.setText(contador);
    }//GEN-LAST:event_formWindowOpened

    private void projectLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectLinkMouseEntered
        // TODO add your handling code here:
        Color c1 = projectLink.getBackground();
        Color c2 = new Color(33, 51, 163);

        if (c1.getRGB() == c2.getRGB()) {
            projectLink.setBackground(new Color(33, 51, 163));
        } else {
            projectLink.setBackground(new Color(57, 76, 190));
        }
    }//GEN-LAST:event_projectLinkMouseEntered

    private void projectLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectLinkMouseExited
        // TODO add your handling code here:
        Color c1 = projectLink.getBackground();
        Color c2 = new Color(33, 51, 163);

        if (c1.getRGB() == c2.getRGB()) {
            projectLink.setBackground(new Color(33, 51, 163));
        } else {
            projectLink.setBackground(new Color(60, 86, 240));
        }
    }//GEN-LAST:event_projectLinkMouseExited

    private void projectLinkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectLinkMouseReleased
        // TODO add your handling code here:
        Color c1 = projectLink.getBackground();
        Color c2 = new Color(57, 76, 190);

        if (c1.getRGB() == c2.getRGB()) {
            projectLink.setBackground(new Color(33, 51, 163));
            userLink.setBackground(new Color(60, 86, 240));
        } else {
            projectLink.setBackground(new Color(60, 86, 240));
            userLink.setBackground(new Color(60, 86, 240));
        }
    }//GEN-LAST:event_projectLinkMouseReleased

    private void userLinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLinkMouseEntered
        // TODO add your handling code here:
        Color c1 = userLink.getBackground();
        Color c2 = new Color(33, 51, 163);

        if (c1.getRGB() == c2.getRGB()) {
            userLink.setBackground(new Color(33, 51, 163));
        } else {
            userLink.setBackground(new Color(57, 76, 190));
        }
    }//GEN-LAST:event_userLinkMouseEntered

    private void userLinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLinkMouseExited
        // TODO add your handling code here:
        Color c1 = userLink.getBackground();
        Color c2 = new Color(33, 51, 163);

        if (c1.getRGB() == c2.getRGB()) {
            userLink.setBackground(new Color(33, 51, 163));
        } else {
            userLink.setBackground(new Color(60, 86, 240));
        }
    }//GEN-LAST:event_userLinkMouseExited

    private void userLinkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLinkMouseReleased
        // TODO add your handling code here:
        Color c1 = userLink.getBackground();
        Color c2 = new Color(57, 76, 190);

        if (c1.getRGB() == c2.getRGB()) {
            userLink.setBackground(new Color(33, 51, 163));
            projectLink.setBackground(new Color(60, 86, 240));
        } else {
            userLink.setBackground(new Color(60, 86, 240));
            projectLink.setBackground(new Color(60, 86, 240));
        }

        //userLink.setBackground(new Color(33, 51, 163));
        //projectLink.setBackground(new Color(60, 86, 240));
    }//GEN-LAST:event_userLinkMouseReleased

    private void newprojectbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newprojectbuttonMouseEntered
        // TODO add your handling code here:
        newprojectbuttonSt1.setVisible(true);
    }//GEN-LAST:event_newprojectbuttonMouseEntered

    private void newprojectbuttonSt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newprojectbuttonSt1MouseClicked
        // TODO add your handling code here:
        newprojectbuttonSt2.setVisible(true);
        
        AddProject ap = new AddProject();
        ap.setVisible(true);
        ap.pack();
        ap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_newprojectbuttonSt1MouseClicked

    private void newprojectbuttonSt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newprojectbuttonSt1MouseExited
        // TODO add your handling code here:
        newprojectbuttonSt1.setVisible(false);
    }//GEN-LAST:event_newprojectbuttonSt1MouseExited

    private void newprojectbuttonSt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newprojectbuttonSt2MouseExited
        // TODO add your handling code here:
        newprojectbuttonSt2.setVisible(false);
    }//GEN-LAST:event_newprojectbuttonSt2MouseExited

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        EditProject ep = new EditProject();
        ep.setVisible(true);
        ep.pack();
        ep.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_editButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        DeleteProject dp = new DeleteProject();
        dp.setVisible(true);
        dp.pack();
        dp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void userLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLinkMouseClicked
        // TODO add your handling code here:
        UsersPanel up = new UsersPanel();
        up.setVisible(true);
        up.pack();
        up.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.dispose();
        
    }//GEN-LAST:event_userLinkMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bluebg;
    private javax.swing.JLabel counter;
    private javax.swing.JLabel counter_box;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTable jTableProjetos;
    private javax.swing.JLabel newprojectbutton;
    private javax.swing.JLabel newprojectbuttonSt1;
    private javax.swing.JLabel newprojectbuttonSt2;
    private javax.swing.JLabel pfpArea;
    private javax.swing.JLabel projectLink;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userLink;
    private javax.swing.JLabel whitebg;
    // End of variables declaration//GEN-END:variables
}
