/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Views;

/**
 *
 * @author Jose Luiz
 */
public class RequirementsPanel extends javax.swing.JFrame {

    /** Creates new form RequirementsPanel */
    public RequirementsPanel() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTableRequisitos = new javax.swing.JTable();
        editRequisitoButton1 = new javax.swing.JButton();
        editRequisitoButton = new javax.swing.JButton();
        removeRequisitoButton = new javax.swing.JButton();
        addRequisitoButton = new javax.swing.JButton();
        requirementTitle = new javax.swing.JLabel();
        projectnameLabel = new javax.swing.JLabel();
        closebutton = new javax.swing.JLabel();
        orangebox = new javax.swing.JLabel();
        whitebg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableRequisitos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Identificador", "Nome", "Módulo", "Funcionalidades", "Data de criação", "Autor", "Data da ultima alteração", "Autor da ultima modificação", "Versão", "Prioridade", "Complexidade", "Esforço estimado (em horas)", "Estado", "Fase", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        getContentPane().add(jTableRequisitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1220, 650));

        editRequisitoButton1.setBackground(new java.awt.Color(60, 86, 240));
        editRequisitoButton1.setForeground(new java.awt.Color(255, 255, 255));
        editRequisitoButton1.setText("Atualizar");
        getContentPane().add(editRequisitoButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 120, 30));

        editRequisitoButton.setBackground(new java.awt.Color(60, 86, 240));
        editRequisitoButton.setForeground(new java.awt.Color(255, 255, 255));
        editRequisitoButton.setText("Editar requisito");
        getContentPane().add(editRequisitoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 740, 120, 30));

        removeRequisitoButton.setBackground(new java.awt.Color(60, 86, 240));
        removeRequisitoButton.setForeground(new java.awt.Color(255, 255, 255));
        removeRequisitoButton.setText("Remover requisito");
        getContentPane().add(removeRequisitoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 740, 120, 30));

        addRequisitoButton.setBackground(new java.awt.Color(60, 86, 240));
        addRequisitoButton.setForeground(new java.awt.Color(255, 255, 255));
        addRequisitoButton.setText("Adicionar requisito");
        getContentPane().add(addRequisitoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 740, 120, 30));

        requirementTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/projectitle_text.png"))); // NOI18N
        getContentPane().add(requirementTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 240, 50));

        projectnameLabel.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        projectnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        projectnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        projectnameLabel.setText("<RESERVADO PARA O NOME DO PROJETO>");
        getContentPane().add(projectnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 310, 50));

        closebutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_adduser/close_icon.png"))); // NOI18N
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 10, 10));

        orangebox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_requirements/orange_box.png"))); // NOI18N
        getContentPane().add(orangebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1280, 70));

        whitebg.setBackground(new java.awt.Color(255, 255, 255));
        whitebg.setOpaque(true);
        whitebg.setPreferredSize(new java.awt.Dimension(1267, 790));
        getContentPane().add(whitebg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_closebuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequirementsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequirementsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequirementsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequirementsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequirementsPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRequisitoButton;
    private javax.swing.JLabel closebutton;
    private javax.swing.JButton editRequisitoButton;
    private javax.swing.JButton editRequisitoButton1;
    private javax.swing.JTable jTableRequisitos;
    private javax.swing.JLabel orangebox;
    private javax.swing.JLabel projectnameLabel;
    private javax.swing.JButton removeRequisitoButton;
    private javax.swing.JLabel requirementTitle;
    private javax.swing.JLabel whitebg;
    // End of variables declaration//GEN-END:variables

}
