/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author renat
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    public Register_Form() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgblue = new javax.swing.JLabel();
        emailfield1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Nome = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        telefone = new javax.swing.JTextField();
        pwdseparator2 = new javax.swing.JSeparator();
        pwdseparator1 = new javax.swing.JSeparator();
        pwdseparator = new javax.swing.JSeparator();
        closebutton = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        Registro = new javax.swing.JLabel();
        pwdfield = new javax.swing.JPasswordField();
        Sobrenome = new javax.swing.JTextField();
        viewpwd = new javax.swing.JCheckBox();
        loginbutton = new javax.swing.JButton();
        bgwhite = new javax.swing.JLabel();
        bgblue1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();
        bgwhite1 = new javax.swing.JLabel();

        bgblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bluebg.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailfield1.setForeground(new java.awt.Color(153, 153, 153));
        emailfield1.setText("Endereço de email");
        emailfield1.setToolTipText("");
        emailfield1.setBorder(null);
        emailfield1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfield1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailfield1FocusLost(evt);
            }
        });
        emailfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfield1ActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 280, 30));

        jSeparator1.setForeground(new java.awt.Color(60, 86, 240));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 280, -1));

        Nome.setForeground(new java.awt.Color(153, 153, 153));
        Nome.setText("Nome");
        Nome.setToolTipText("");
        Nome.setBorder(null);
        Nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NomeFocusLost(evt);
            }
        });
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        getContentPane().add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, 280, 30));

        jSeparator2.setForeground(new java.awt.Color(60, 86, 240));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 280, -1));

        telefone.setForeground(new java.awt.Color(153, 153, 153));
        telefone.setText("Telefone");
        telefone.setToolTipText("");
        telefone.setBorder(null);
        telefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                telefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                telefoneFocusLost(evt);
            }
        });
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 280, 30));

        pwdseparator2.setForeground(new java.awt.Color(60, 86, 240));
        getContentPane().add(pwdseparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 280, 10));

        pwdseparator1.setForeground(new java.awt.Color(60, 86, 240));
        getContentPane().add(pwdseparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 280, 10));

        pwdseparator.setForeground(new java.awt.Color(60, 86, 240));
        getContentPane().add(pwdseparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 280, 10));

        closebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close-button.png"))); // NOI18N
        closebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebuttonMouseClicked(evt);
            }
        });
        getContentPane().add(closebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, 20, 20));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logodescricao.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 730));

        Registro.setText("Registro");
        getContentPane().add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 20, -1, -1));

        pwdfield.setForeground(new java.awt.Color(153, 153, 153));
        pwdfield.setText("testetestete");
        pwdfield.setToolTipText("");
        pwdfield.setBorder(null);
        pwdfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdfieldFocusLost(evt);
            }
        });
        pwdfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdfieldActionPerformed(evt);
            }
        });
        getContentPane().add(pwdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 280, 30));

        Sobrenome.setForeground(new java.awt.Color(153, 153, 153));
        Sobrenome.setText("Sobrenome");
        Sobrenome.setToolTipText("");
        Sobrenome.setBorder(null);
        Sobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SobrenomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SobrenomeFocusLost(evt);
            }
        });
        Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 280, 30));

        viewpwd.setBackground(new java.awt.Color(255, 255, 255));
        viewpwd.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        viewpwd.setText("Ver/ocultar senha");
        viewpwd.setToolTipText("");
        viewpwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewpwdMouseClicked(evt);
            }
        });
        viewpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpwdActionPerformed(evt);
            }
        });
        getContentPane().add(viewpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, -1));

        loginbutton.setBackground(new java.awt.Color(60, 86, 240));
        loginbutton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(240, 240, 240));
        loginbutton.setText("Cadastrar");
        loginbutton.setBorder(null);
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbuttonMouseExited(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 280, 50));

        bgwhite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whitebg.png"))); // NOI18N
        getContentPane().add(bgwhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -30, 710, 790));

        bgblue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bluebg.png"))); // NOI18N
        getContentPane().add(bgblue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 600, 790));
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 790));

        bgwhite1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/whitebg.png"))); // NOI18N
        getContentPane().add(bgwhite1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, -30, 710, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pwdfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdfieldFocusGained
        // TODO add your handling code here:
        //pwdfield.setText("");

        String pass = String.valueOf(pwdfield.getPassword());

        if(pass.trim().equals("testetestete")){
            pwdfield.setText("");
            pwdfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwdfieldFocusGained

    private void pwdfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdfieldFocusLost
        // TODO add your handling code here:

        String pass = String.valueOf(pwdfield.getPassword());

        if(pass.trim().equals("") || pass.trim().equals("testetestete")){
            pwdfield.setText("testetestete");
            pwdfield.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_pwdfieldFocusLost

    private void pwdfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdfieldActionPerformed

    private void SobrenomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SobrenomeFocusGained
        // TODO add your handling code here:
        //emailfield.setText("");
        if(Sobrenome.getText().trim().equals("Endereço de email")){
            Sobrenome.setText("");
            Sobrenome.setForeground(Color.black);
        }
    }//GEN-LAST:event_SobrenomeFocusGained

    private void SobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SobrenomeFocusLost
        // TODO add your handling code here:
        if(Sobrenome.getText().trim().equals("") || Sobrenome.getText().trim().equals("Endereço de email")){
            Sobrenome.setText("Endereço de email");
            Sobrenome.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_SobrenomeFocusLost

    private void SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobrenomeActionPerformed

    private void viewpwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpwdMouseClicked
        // TODO add your handling code here:
        if(viewpwd.isSelected()){
            pwdfield.setEchoChar((char)0);
        }else{
            pwdfield.setEchoChar('*');
        }
    }//GEN-LAST:event_viewpwdMouseClicked

    private void viewpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewpwdActionPerformed

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_loginbuttonMouseClicked

    private void loginbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseEntered
        // TODO add your handling code here:
        loginbutton.setBackground(new Color(33, 51, 163));
    }//GEN-LAST:event_loginbuttonMouseEntered

    private void loginbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbuttonMouseExited
        // TODO add your handling code here:
        loginbutton.setBackground(new Color(60, 84, 240));
    }//GEN-LAST:event_loginbuttonMouseExited

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;

        String email = Sobrenome.getText();
        String password = String.valueOf(pwdfield.getPassword());

        String query = "SELECT * FROM `users` WHERE `email` = ? AND `password`= ?";

        try {
            st = ConnectionFactory.getConnection().prepareStatement(query);

            st.setString(1, email);
            st.setString(2, password);
            rs = st.executeQuery();

            if(rs.next()){
                // mostrar um novo formulario
                Menu form = new Menu();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                // fechar o formulario de login atual form(login form)
                this.dispose();

            }else{
                // exibir mensagem de erro
                JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos", "Erro", 2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_loginbuttonActionPerformed

    private void closebuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebuttonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closebuttonMouseClicked

    private void emailfield1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfield1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield1FocusGained

    private void emailfield1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfield1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield1FocusLost

    private void emailfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfield1ActionPerformed

    private void NomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFocusGained

    private void NomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NomeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFocusLost

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void telefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFocusGained

    private void telefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_telefoneFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFocusLost

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JTextField Nome;
    private javax.swing.JLabel Registro;
    private javax.swing.JTextField Sobrenome;
    private javax.swing.JLabel bgblue;
    private javax.swing.JLabel bgblue1;
    private javax.swing.JLabel bgwhite;
    private javax.swing.JLabel bgwhite1;
    private javax.swing.JLabel closebutton;
    private javax.swing.JTextField emailfield1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField pwdfield;
    private javax.swing.JSeparator pwdseparator;
    private javax.swing.JSeparator pwdseparator1;
    private javax.swing.JSeparator pwdseparator2;
    private javax.swing.JTextField telefone;
    private javax.swing.JCheckBox viewpwd;
    // End of variables declaration//GEN-END:variables
}
